namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_API_BASE_URL: string;
    NEXT_PUBLIC_SEATS_WORKSPACE_KEY: string;
    NEXT_PUBLIC_FIREBASE_API_KEY: string;
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
    NEXT_PUBLIC_FIREBASE_APP_ID: string;
    NEXT_PUBLIC_FIREBASE_PHONE_AUTH_TESTING?: "true" | "false";
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID?: string;
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET?: string;
    NEXT_PUBLIC_SECRET_BASE_32: string;
    NEXT_PUBLIC_BASE_PATH: string;
    NEXT_PUBLIC_ASSET_PREFIX: string;
    DOCKER_IMAGE_VERSION?: string;
    FIREBASE_SERVICE_ACCOUNT_JSON?: string;
    FIREBASE_SESSION_COOKIE_NAME?: string;
    FIREBASE_SESSION_COOKIE_SECURE?: "true" | "false";
  }
}
